### ISSUE TITLE
Error: markTarget is not defined &  error running hook for S_SPAWN_USER

### ISSUE THREAD

**Issue by littleguideboi** [Fukki/auto-target#2]
[19:41:23.002] [dispatch] [auto target] handle: error running hook for S_SPAWN_USER<15>
hook: (anonymous) in auto target
data: {
  serverId: 38,
  playerId: 859,
  gameId: 72198331528781006n,
  loc: Vec3 { x: 93609.4296875, y: -88736.46875, z: -4568 },
  w: 2.895292863334905,
  relation: 1,
  templateId: 10801,
  huntingZoneId: 0,
  walkSpeed: 52,
  runSpeed: 224,
  actionMode: 0,
  status: 0,
  visible: true,
  alive: true,
  appearance: Customize {
    unk: 101,
    skinColor: 16,
    faceStyle: 4,
    faceDecal: 3,
    hairStyle: 16,
    hairColor: 32,
    voice: 4,
    tattoos: 0
  },
  weapon: 89693,
  body: 89721,
  hand: 89646,
  feet: 89733,
  underwear: 98182,
  head: 88863,
  face: 88868,
  spawnFx: 1,
  mount: 0,
  pose: 7,
  title: 0,
  shuttleId: 0n,
  guildLogoId: 0,
  exarch: false,
  gm: false,
  gmInvisible: false,
  weaponModel: 0,
  bodyModel: 0,
  handModel: 0,
  feetModel: 0,
  weaponDye: 0,
  bodyDye: 0,
  handDye: 0,
  feetDye: 0,
  underwearDye: 0,
  styleBackDye: 0,
  styleHeadDye: 0,
  styleFaceDye: 0,
  weaponEnchant: 12,
  isWorldEventTarget: false,
  pkEnabled: false,
  level: 70,
  vehicleEx: 0n,
  showFace: false,
  styleHead: 50019,
  styleFace: 151832,
  styleBack: 0,
  styleWeapon: 153484,
  styleBody: 257116,
  styleFootprint: 0,
  styleHeadScale: 1,
  styleHeadRotation: Vec3 { x: 0, y: 0, z: 0 },
  styleHeadTranslation: Vec3 { x: 0, y: 0, z: 0 },
  styleHeadTranslationDebug: Vec3 { x: 0, y: 0, z: 0 },
  styleFaceScale: 1,
  styleFaceRotation: Vec3 { x: 0, y: 0, z: 0 },
  styleFaceTranslation: Vec3 { x: 0, y: 0, z: 0 },
  styleFaceTranslationDebug: Vec3 { x: 0, y: 0, z: 0 },
  styleBackScale: 1,
  styleBackRotation: Vec3 { x: 0, y: 0, z: 0 },
  styleBackTranslation: Vec3 { x: 0, y: 0, z: 0 },
  styleBackTranslationDebug: Vec3 { x: 0, y: 0, z: 0 },
  usedStyleHeadTransform: false,
  styleBodyDye: 0,
  partyServer: 0,
  partyId: 0,
  raid: false,
  showStyle: true,
  titleCount: 0n,
  appearance2: 100,
  scale: 1,
  icons: [ 21 ],
  accountBenefits: [ 434, 88888888 ],
  name: 'Tafiana',
  guildName: 'Score',
  guildRank: 'Core member',
  details: <Buffer 03 10 10 03 00 00 00 00 1a 10 10 00 10 10 10 00 08 10 0a 10 0c 17 10 08 13 13 1f 0a 1a 10 0b 10>,
  guildLogo: 'guildlogo_38_11390_465',
  shape: <Buffer 01 0e 10 0e 0e 10 11 11 11 0f 0e 0e 0e 0f 0f 0f 10 13 0a 00 10 10 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 14 more bytes>
}
error: markTarget is not defined
    at Object.callback (D:\Tera Related\TeraToolBox\mods\auto-target\index.js:1:300355)
![image](https://user-images.githubusercontent.com/36592382/82473523-5cdcb800-9ad2-11ea-9359-0396fd5d2b2e.png)

**Comment by nightforgex** [comment]
just adding that this happens when any user spawns after your most recent update, regardless of name or guild.

**Comment by desh27** [comment]
+

**Comment by desh27** [comment]
same problem...

**Comment by Fukki** [comment]
sorry the problem is my wrong coding
long time not edit this maybe missing something
auto target added new config in auto mark "enable": false
because someone no need auto mark enemy target

you can add it with your self in config or delete config 
and let auto-target generate new config again
```
"markTarget": {
        "enable": false <- here this line (delete this comment before saved)
        "Alliance": {
            "0": [],
            "1": [],
            "2": []
        },
        "Enemy": {
            "0": [
                6,
                7
            ],
            "1": [],
            "2": []
        }
