### ISSUE TITLE
Anti-virus detection

### ISSUE THREAD

**Issue by Zigadirasu** [Fukki/auto-target#23]
my windows defender says there is a trojan in the index.js file, found wierd since other modules arent triggered and neither before.  is it true?

**Comment by Loliconera** [comment]
I also get the same message

**Comment by Fukki** [comment]
go buy better anti virus
windows defender always fuck off all files
https://www.virustotal.com/gui/file/8ff5baf5065040e769cd94b7bed6273e9d95318c224167cdfdd4552fde7c6377/detection

**Comment by Zigadirasu** [comment]
yeah thought i so, didnt stoped to use even after.

**Comment by Fukki** [comment]
or set exlusions

![image](https://user-images.githubusercontent.com/26898177/131874860-bad3263f-76c4-4a9f-bfab-497557d05b35.png)
