### ISSUE TITLE
Breaks when party composition changes

### ISSUE THREAD

**Issue by kira112234** [Fukki/auto-target#24]
After 30 Aug patch, does not work if party member log out and in, or if new member joins. eg healer targeted skills

**Comment by Fukki** [comment]
hmm it still work
auto target different from auto heal abit
make sure your friend are move or use some skill
auto target will update location and dist after that
but auto heal update player dist after press skill

**Comment by Fukki** [comment]
it still work fine
make sure your friend are move or use some skill
auto-target need location update after that
