### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by PepegaHah** [Fukki/auto-target#5]
Hello there,

When you change some numbers in config (for example hp cut off and deleting some lines like npc, enemy-all) after you save and enter the game, it goes back to original again. (Even if you disable auto-update). Would be nice if you can look into that:)

**Comment by Midoriykawa** [comment]
lease contact the module's author: https://github.com/Fukki/auto-target/issues/
[11:19:40.281] Error: [dispatch] [auto target] hook: unmapped packet "S_BOSS_BATTLE_INFO"

**Comment by Midoriykawa** [comment]
Shakan

**Comment by Fukki** [comment]
check your config syntax
many pepole missing hyphen

**Comment by PepegaHah** [comment]
Fukki,
I am so sorry to disturb again. I've re-downloaded your auto-target module.
As i noticed it still turning config changed to back. I didn't touch
anything. Literally nothing. How can i fix this.
I am not a coder or smth therefore i didnt understand this : "check your
config syntax many pepole missing hyphen".  Mind if i ask if you can help
me? Would appreciate your help.
