### ISSUE TITLE
Something's borked in the current NA patch

### ISSUE THREAD

**Issue by CakeWizard** [Fukki/auto-target#5]
![electron_0MS1HGWsb0](https://user-images.githubusercontent.com/12159005/74297219-cbf48480-4d0b-11ea-9daf-5b457dcd16c5.png)

This is all it tells me. After disabling auto-target, game launches flawlessly.

**Comment by Fukki** [comment]
some ppl got crash but idk what is happen
่just guess the problem from SP :/

btw i try many time before release
it's not crash and any problem

i will fix a little soon 
not have full logs error so just fix with my guessed

**Comment by CakeWizard** [comment]
Do you know of any debug module I could run to get at least some information about the crash? If there's anything more I can do to help I'll be happy to. Besides work on the code itself, because I looked through it, and JavaScript hurts my brain. Well, anything programming related hurts my brain so no surprise there really.
