### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by unlimitedgtx** [Fukki/auto-target#9]
Solved

**Comment by Fukki** [comment]
hmm what is pr

**Comment by Midoriykawa** [comment]
skill pridiction

**Comment by unlimitedgtx** [comment]
Jep meant sp, autocorrection

**Comment by littleguideboi** [comment]
no pr is "Ping Remover" from Kasea. And automated thing doesn't work with it

**Comment by Midoriykawa** [comment]
I checked, everything works well on mysticism and priest
